import { FontConfig } from "../types/wedding";
import { colorSwatcher } from "./ColorSwatcher";

export const FontConfigPresets = {
    empty: {} as FontConfig,

    "white-Baskerville-normal-0_750": {
        color: colorSwatcher.white,
        fontFamily: "Baskerville",
        fontStyle: "normal",
        fontSize: 0.75,
    } as FontConfig,
    "white-Baskerville-normal-0_875": {
        color: colorSwatcher.white,
        fontFamily: "Baskerville",
        fontStyle: "normal",
        fontSize: 0.875,
    } as FontConfig,
    "white-Baskerville-normal-1_000": {
        color: colorSwatcher.white,
        fontFamily: "Baskerville",
        fontStyle: "normal",
        fontSize: 1.0,
    } as FontConfig,
    "white-Baskerville-normal-1_125": {
        color: colorSwatcher.white,
        fontFamily: "Baskerville",
        fontStyle: "normal",
        fontSize: 1.125,
    } as FontConfig,
    "white-Baskerville-normal-1_250": {
        color: colorSwatcher.white,
        fontFamily: "Baskerville",
        fontStyle: "normal",
        fontSize: 1.25,
    } as FontConfig,
    "white-Baskerville-normal-1_375": {
        color: colorSwatcher.white,
        fontFamily: "Baskerville",
        fontStyle: "normal",
        fontSize: 1.375,
    } as FontConfig,
    "white-Baskerville-normal-1_500": {
        color: colorSwatcher.white,
        fontFamily: "Baskerville",
        fontStyle: "normal",
        fontSize: 1.5,
    } as FontConfig,
    "white-Baskerville-normal-1_625": {
        color: colorSwatcher.white,
        fontFamily: "Baskerville",
        fontStyle: "normal",
        fontSize: 1.625,
    } as FontConfig,
    "white-Baskerville-normal-1_750": {
        color: colorSwatcher.white,
        fontFamily: "Baskerville",
        fontStyle: "normal",
        fontSize: 1.75,
    } as FontConfig,
    "white-Baskerville-normal-1_875": {
        color: colorSwatcher.white,
        fontFamily: "Baskerville",
        fontStyle: "normal",
        fontSize: 1.875,
    } as FontConfig,
    "white-Baskerville-normal-2_000": {
        color: colorSwatcher.white,
        fontFamily: "Baskerville",
        fontStyle: "normal",
        fontSize: 2.0,
    } as FontConfig,
    "white-Baskerville-normal-2_125": {
        color: colorSwatcher.white,
        fontFamily: "Baskerville",
        fontStyle: "normal",
        fontSize: 2.125,
    } as FontConfig,
    "white-Baskerville-normal-2_250": {
        color: colorSwatcher.white,
        fontFamily: "Baskerville",
        fontStyle: "normal",
        fontSize: 2.25,
    } as FontConfig,
    "white-Baskerville-normal-2_375": {
        color: colorSwatcher.white,
        fontFamily: "Baskerville",
        fontStyle: "normal",
        fontSize: 2.375,
    } as FontConfig,
    "white-Baskerville-normal-2_500": {
        color: colorSwatcher.white,
        fontFamily: "Baskerville",
        fontStyle: "normal",
        fontSize: 2.5,
    } as FontConfig,
    "white-Baskerville-normal-2_625": {
        color: colorSwatcher.white,
        fontFamily: "Baskerville",
        fontStyle: "normal",
        fontSize: 2.625,
    } as FontConfig,
    "white-Baskerville-normal-2_750": {
        color: colorSwatcher.white,
        fontFamily: "Baskerville",
        fontStyle: "normal",
        fontSize: 2.75,
    } as FontConfig,
    "white-Baskerville-normal-2_875": {
        color: colorSwatcher.white,
        fontFamily: "Baskerville",
        fontStyle: "normal",
        fontSize: 2.875,
    } as FontConfig,
    "white-Baskerville-normal-3_000": {
        color: colorSwatcher.white,
        fontFamily: "Baskerville",
        fontStyle: "normal",
        fontSize: 3.0,
    } as FontConfig,
    "white-Baskerville-italic-0_750": {
        color: colorSwatcher.white,
        fontFamily: "Baskerville",
        fontStyle: "italic",
        fontSize: 0.75,
    } as FontConfig,
    "white-Baskerville-italic-0_875": {
        color: colorSwatcher.white,
        fontFamily: "Baskerville",
        fontStyle: "italic",
        fontSize: 0.875,
    } as FontConfig,
    "white-Baskerville-italic-1_000": {
        color: colorSwatcher.white,
        fontFamily: "Baskerville",
        fontStyle: "italic",
        fontSize: 1.0,
    } as FontConfig,
    "white-Baskerville-italic-1_125": {
        color: colorSwatcher.white,
        fontFamily: "Baskerville",
        fontStyle: "italic",
        fontSize: 1.125,
    } as FontConfig,
    "white-Baskerville-italic-1_250": {
        color: colorSwatcher.white,
        fontFamily: "Baskerville",
        fontStyle: "italic",
        fontSize: 1.25,
    } as FontConfig,
    "white-Baskerville-italic-1_375": {
        color: colorSwatcher.white,
        fontFamily: "Baskerville",
        fontStyle: "italic",
        fontSize: 1.375,
    } as FontConfig,
    "white-Baskerville-italic-1_500": {
        color: colorSwatcher.white,
        fontFamily: "Baskerville",
        fontStyle: "italic",
        fontSize: 1.5,
    } as FontConfig,
    "white-Baskerville-italic-1_625": {
        color: colorSwatcher.white,
        fontFamily: "Baskerville",
        fontStyle: "italic",
        fontSize: 1.625,
    } as FontConfig,
    "white-Baskerville-italic-1_750": {
        color: colorSwatcher.white,
        fontFamily: "Baskerville",
        fontStyle: "italic",
        fontSize: 1.75,
    } as FontConfig,
    "white-Baskerville-italic-1_875": {
        color: colorSwatcher.white,
        fontFamily: "Baskerville",
        fontStyle: "italic",
        fontSize: 1.875,
    } as FontConfig,
    "white-Baskerville-italic-2_000": {
        color: colorSwatcher.white,
        fontFamily: "Baskerville",
        fontStyle: "italic",
        fontSize: 2.0,
    } as FontConfig,
    "white-Baskerville-italic-2_125": {
        color: colorSwatcher.white,
        fontFamily: "Baskerville",
        fontStyle: "italic",
        fontSize: 2.125,
    } as FontConfig,
    "white-Baskerville-italic-2_250": {
        color: colorSwatcher.white,
        fontFamily: "Baskerville",
        fontStyle: "italic",
        fontSize: 2.25,
    } as FontConfig,
    "white-Baskerville-italic-2_375": {
        color: colorSwatcher.white,
        fontFamily: "Baskerville",
        fontStyle: "italic",
        fontSize: 2.375,
    } as FontConfig,
    "white-Baskerville-italic-2_500": {
        color: colorSwatcher.white,
        fontFamily: "Baskerville",
        fontStyle: "italic",
        fontSize: 2.5,
    } as FontConfig,
    "white-Baskerville-italic-2_625": {
        color: colorSwatcher.white,
        fontFamily: "Baskerville",
        fontStyle: "italic",
        fontSize: 2.625,
    } as FontConfig,
    "white-Baskerville-italic-2_750": {
        color: colorSwatcher.white,
        fontFamily: "Baskerville",
        fontStyle: "italic",
        fontSize: 2.75,
    } as FontConfig,
    "white-Baskerville-italic-2_875": {
        color: colorSwatcher.white,
        fontFamily: "Baskerville",
        fontStyle: "italic",
        fontSize: 2.875,
    } as FontConfig,
    "white-Baskerville-italic-3_000": {
        color: colorSwatcher.white,
        fontFamily: "Baskerville",
        fontStyle: "italic",
        fontSize: 3.0,
    } as FontConfig,
    "white-Ridi-normal-0_750": {
        color: colorSwatcher.white,
        fontFamily: "Ridi",
        fontStyle: "normal",
        fontSize: 0.75,
    } as FontConfig,
    "white-Ridi-normal-0_875": {
        color: colorSwatcher.white,
        fontFamily: "Ridi",
        fontStyle: "normal",
        fontSize: 0.875,
    } as FontConfig,
    "white-Ridi-normal-1_000": {
        color: colorSwatcher.white,
        fontFamily: "Ridi",
        fontStyle: "normal",
        fontSize: 1.0,
    } as FontConfig,
    "white-Ridi-normal-1_125": {
        color: colorSwatcher.white,
        fontFamily: "Ridi",
        fontStyle: "normal",
        fontSize: 1.125,
    } as FontConfig,
    "white-Ridi-normal-1_250": {
        color: colorSwatcher.white,
        fontFamily: "Ridi",
        fontStyle: "normal",
        fontSize: 1.25,
    } as FontConfig,
    "white-Ridi-normal-1_375": {
        color: colorSwatcher.white,
        fontFamily: "Ridi",
        fontStyle: "normal",
        fontSize: 1.375,
    } as FontConfig,
    "white-Ridi-normal-1_500": {
        color: colorSwatcher.white,
        fontFamily: "Ridi",
        fontStyle: "normal",
        fontSize: 1.5,
    } as FontConfig,
    "white-Ridi-normal-1_625": {
        color: colorSwatcher.white,
        fontFamily: "Ridi",
        fontStyle: "normal",
        fontSize: 1.625,
    } as FontConfig,
    "white-Ridi-normal-1_750": {
        color: colorSwatcher.white,
        fontFamily: "Ridi",
        fontStyle: "normal",
        fontSize: 1.75,
    } as FontConfig,
    "white-Ridi-normal-1_875": {
        color: colorSwatcher.white,
        fontFamily: "Ridi",
        fontStyle: "normal",
        fontSize: 1.875,
    } as FontConfig,
    "white-Ridi-normal-2_000": {
        color: colorSwatcher.white,
        fontFamily: "Ridi",
        fontStyle: "normal",
        fontSize: 2.0,
    } as FontConfig,
    "white-Ridi-normal-2_125": {
        color: colorSwatcher.white,
        fontFamily: "Ridi",
        fontStyle: "normal",
        fontSize: 2.125,
    } as FontConfig,
    "white-Ridi-normal-2_250": {
        color: colorSwatcher.white,
        fontFamily: "Ridi",
        fontStyle: "normal",
        fontSize: 2.25,
    } as FontConfig,
    "white-Ridi-normal-2_375": {
        color: colorSwatcher.white,
        fontFamily: "Ridi",
        fontStyle: "normal",
        fontSize: 2.375,
    } as FontConfig,
    "white-Ridi-normal-2_500": {
        color: colorSwatcher.white,
        fontFamily: "Ridi",
        fontStyle: "normal",
        fontSize: 2.5,
    } as FontConfig,
    "white-Ridi-normal-2_625": {
        color: colorSwatcher.white,
        fontFamily: "Ridi",
        fontStyle: "normal",
        fontSize: 2.625,
    } as FontConfig,
    "white-Ridi-normal-2_750": {
        color: colorSwatcher.white,
        fontFamily: "Ridi",
        fontStyle: "normal",
        fontSize: 2.75,
    } as FontConfig,
    "white-Ridi-normal-2_875": {
        color: colorSwatcher.white,
        fontFamily: "Ridi",
        fontStyle: "normal",
        fontSize: 2.875,
    } as FontConfig,
    "white-Ridi-normal-3_000": {
        color: colorSwatcher.white,
        fontFamily: "Ridi",
        fontStyle: "normal",
        fontSize: 3.0,
    } as FontConfig,
    "white-Ridi-italic-0_750": {
        color: colorSwatcher.white,
        fontFamily: "Ridi",
        fontStyle: "italic",
        fontSize: 0.75,
    } as FontConfig,
    "white-Ridi-italic-0_875": {
        color: colorSwatcher.white,
        fontFamily: "Ridi",
        fontStyle: "italic",
        fontSize: 0.875,
    } as FontConfig,
    "white-Ridi-italic-1_000": {
        color: colorSwatcher.white,
        fontFamily: "Ridi",
        fontStyle: "italic",
        fontSize: 1.0,
    } as FontConfig,
    "white-Ridi-italic-1_125": {
        color: colorSwatcher.white,
        fontFamily: "Ridi",
        fontStyle: "italic",
        fontSize: 1.125,
    } as FontConfig,
    "white-Ridi-italic-1_250": {
        color: colorSwatcher.white,
        fontFamily: "Ridi",
        fontStyle: "italic",
        fontSize: 1.25,
    } as FontConfig,
    "white-Ridi-italic-1_375": {
        color: colorSwatcher.white,
        fontFamily: "Ridi",
        fontStyle: "italic",
        fontSize: 1.375,
    } as FontConfig,
    "white-Ridi-italic-1_500": {
        color: colorSwatcher.white,
        fontFamily: "Ridi",
        fontStyle: "italic",
        fontSize: 1.5,
    } as FontConfig,
    "white-Ridi-italic-1_625": {
        color: colorSwatcher.white,
        fontFamily: "Ridi",
        fontStyle: "italic",
        fontSize: 1.625,
    } as FontConfig,
    "white-Ridi-italic-1_750": {
        color: colorSwatcher.white,
        fontFamily: "Ridi",
        fontStyle: "italic",
        fontSize: 1.75,
    } as FontConfig,
    "white-Ridi-italic-1_875": {
        color: colorSwatcher.white,
        fontFamily: "Ridi",
        fontStyle: "italic",
        fontSize: 1.875,
    } as FontConfig,
    "white-Ridi-italic-2_000": {
        color: colorSwatcher.white,
        fontFamily: "Ridi",
        fontStyle: "italic",
        fontSize: 2.0,
    } as FontConfig,
    "white-Ridi-italic-2_125": {
        color: colorSwatcher.white,
        fontFamily: "Ridi",
        fontStyle: "italic",
        fontSize: 2.125,
    } as FontConfig,
    "white-Ridi-italic-2_250": {
        color: colorSwatcher.white,
        fontFamily: "Ridi",
        fontStyle: "italic",
        fontSize: 2.25,
    } as FontConfig,
    "white-Ridi-italic-2_375": {
        color: colorSwatcher.white,
        fontFamily: "Ridi",
        fontStyle: "italic",
        fontSize: 2.375,
    } as FontConfig,
    "white-Ridi-italic-2_500": {
        color: colorSwatcher.white,
        fontFamily: "Ridi",
        fontStyle: "italic",
        fontSize: 2.5,
    } as FontConfig,
    "white-Ridi-italic-2_625": {
        color: colorSwatcher.white,
        fontFamily: "Ridi",
        fontStyle: "italic",
        fontSize: 2.625,
    } as FontConfig,
    "white-Ridi-italic-2_750": {
        color: colorSwatcher.white,
        fontFamily: "Ridi",
        fontStyle: "italic",
        fontSize: 2.75,
    } as FontConfig,
    "white-Ridi-italic-2_875": {
        color: colorSwatcher.white,
        fontFamily: "Ridi",
        fontStyle: "italic",
        fontSize: 2.875,
    } as FontConfig,
    "white-Ridi-italic-3_000": {
        color: colorSwatcher.white,
        fontFamily: "Ridi",
        fontStyle: "italic",
        fontSize: 3.0,
    } as FontConfig,
    "black-Baskerville-normal-0_750": {
        color: colorSwatcher.black,
        fontFamily: "Baskerville",
        fontStyle: "normal",
        fontSize: 0.75,
    } as FontConfig,
    "black-Baskerville-normal-0_875": {
        color: colorSwatcher.black,
        fontFamily: "Baskerville",
        fontStyle: "normal",
        fontSize: 0.875,
    } as FontConfig,
    "black-Baskerville-normal-1_000": {
        color: colorSwatcher.black,
        fontFamily: "Baskerville",
        fontStyle: "normal",
        fontSize: 1.0,
    } as FontConfig,
    "black-Baskerville-normal-1_125": {
        color: colorSwatcher.black,
        fontFamily: "Baskerville",
        fontStyle: "normal",
        fontSize: 1.125,
    } as FontConfig,
    "black-Baskerville-normal-1_250": {
        color: colorSwatcher.black,
        fontFamily: "Baskerville",
        fontStyle: "normal",
        fontSize: 1.25,
    } as FontConfig,
    "black-Baskerville-normal-1_375": {
        color: colorSwatcher.black,
        fontFamily: "Baskerville",
        fontStyle: "normal",
        fontSize: 1.375,
    } as FontConfig,
    "black-Baskerville-normal-1_500": {
        color: colorSwatcher.black,
        fontFamily: "Baskerville",
        fontStyle: "normal",
        fontSize: 1.5,
    } as FontConfig,
    "black-Baskerville-normal-1_625": {
        color: colorSwatcher.black,
        fontFamily: "Baskerville",
        fontStyle: "normal",
        fontSize: 1.625,
    } as FontConfig,
    "black-Baskerville-normal-1_750": {
        color: colorSwatcher.black,
        fontFamily: "Baskerville",
        fontStyle: "normal",
        fontSize: 1.75,
    } as FontConfig,
    "black-Baskerville-normal-1_875": {
        color: colorSwatcher.black,
        fontFamily: "Baskerville",
        fontStyle: "normal",
        fontSize: 1.875,
    } as FontConfig,
    "black-Baskerville-normal-2_000": {
        color: colorSwatcher.black,
        fontFamily: "Baskerville",
        fontStyle: "normal",
        fontSize: 2.0,
    } as FontConfig,
    "black-Baskerville-normal-2_125": {
        color: colorSwatcher.black,
        fontFamily: "Baskerville",
        fontStyle: "normal",
        fontSize: 2.125,
    } as FontConfig,
    "black-Baskerville-normal-2_250": {
        color: colorSwatcher.black,
        fontFamily: "Baskerville",
        fontStyle: "normal",
        fontSize: 2.25,
    } as FontConfig,
    "black-Baskerville-normal-2_375": {
        color: colorSwatcher.black,
        fontFamily: "Baskerville",
        fontStyle: "normal",
        fontSize: 2.375,
    } as FontConfig,
    "black-Baskerville-normal-2_500": {
        color: colorSwatcher.black,
        fontFamily: "Baskerville",
        fontStyle: "normal",
        fontSize: 2.5,
    } as FontConfig,
    "black-Baskerville-normal-2_625": {
        color: colorSwatcher.black,
        fontFamily: "Baskerville",
        fontStyle: "normal",
        fontSize: 2.625,
    } as FontConfig,
    "black-Baskerville-normal-2_750": {
        color: colorSwatcher.black,
        fontFamily: "Baskerville",
        fontStyle: "normal",
        fontSize: 2.75,
    } as FontConfig,
    "black-Baskerville-normal-2_875": {
        color: colorSwatcher.black,
        fontFamily: "Baskerville",
        fontStyle: "normal",
        fontSize: 2.875,
    } as FontConfig,
    "black-Baskerville-normal-3_000": {
        color: colorSwatcher.black,
        fontFamily: "Baskerville",
        fontStyle: "normal",
        fontSize: 3.0,
    } as FontConfig,
    "black-Baskerville-italic-0_750": {
        color: colorSwatcher.black,
        fontFamily: "Baskerville",
        fontStyle: "italic",
        fontSize: 0.75,
    } as FontConfig,
    "black-Baskerville-italic-0_875": {
        color: colorSwatcher.black,
        fontFamily: "Baskerville",
        fontStyle: "italic",
        fontSize: 0.875,
    } as FontConfig,
    "black-Baskerville-italic-1_000": {
        color: colorSwatcher.black,
        fontFamily: "Baskerville",
        fontStyle: "italic",
        fontSize: 1.0,
    } as FontConfig,
    "black-Baskerville-italic-1_125": {
        color: colorSwatcher.black,
        fontFamily: "Baskerville",
        fontStyle: "italic",
        fontSize: 1.125,
    } as FontConfig,
    "black-Baskerville-italic-1_250": {
        color: colorSwatcher.black,
        fontFamily: "Baskerville",
        fontStyle: "italic",
        fontSize: 1.25,
    } as FontConfig,
    "black-Baskerville-italic-1_375": {
        color: colorSwatcher.black,
        fontFamily: "Baskerville",
        fontStyle: "italic",
        fontSize: 1.375,
    } as FontConfig,
    "black-Baskerville-italic-1_500": {
        color: colorSwatcher.black,
        fontFamily: "Baskerville",
        fontStyle: "italic",
        fontSize: 1.5,
    } as FontConfig,
    "black-Baskerville-italic-1_625": {
        color: colorSwatcher.black,
        fontFamily: "Baskerville",
        fontStyle: "italic",
        fontSize: 1.625,
    } as FontConfig,
    "black-Baskerville-italic-1_750": {
        color: colorSwatcher.black,
        fontFamily: "Baskerville",
        fontStyle: "italic",
        fontSize: 1.75,
    } as FontConfig,
    "black-Baskerville-italic-1_875": {
        color: colorSwatcher.black,
        fontFamily: "Baskerville",
        fontStyle: "italic",
        fontSize: 1.875,
    } as FontConfig,
    "black-Baskerville-italic-2_000": {
        color: colorSwatcher.black,
        fontFamily: "Baskerville",
        fontStyle: "italic",
        fontSize: 2.0,
    } as FontConfig,
    "black-Baskerville-italic-2_125": {
        color: colorSwatcher.black,
        fontFamily: "Baskerville",
        fontStyle: "italic",
        fontSize: 2.125,
    } as FontConfig,
    "black-Baskerville-italic-2_250": {
        color: colorSwatcher.black,
        fontFamily: "Baskerville",
        fontStyle: "italic",
        fontSize: 2.25,
    } as FontConfig,
    "black-Baskerville-italic-2_375": {
        color: colorSwatcher.black,
        fontFamily: "Baskerville",
        fontStyle: "italic",
        fontSize: 2.375,
    } as FontConfig,
    "black-Baskerville-italic-2_500": {
        color: colorSwatcher.black,
        fontFamily: "Baskerville",
        fontStyle: "italic",
        fontSize: 2.5,
    } as FontConfig,
    "black-Baskerville-italic-2_625": {
        color: colorSwatcher.black,
        fontFamily: "Baskerville",
        fontStyle: "italic",
        fontSize: 2.625,
    } as FontConfig,
    "black-Baskerville-italic-2_750": {
        color: colorSwatcher.black,
        fontFamily: "Baskerville",
        fontStyle: "italic",
        fontSize: 2.75,
    } as FontConfig,
    "black-Baskerville-italic-2_875": {
        color: colorSwatcher.black,
        fontFamily: "Baskerville",
        fontStyle: "italic",
        fontSize: 2.875,
    } as FontConfig,
    "black-Baskerville-italic-3_000": {
        color: colorSwatcher.black,
        fontFamily: "Baskerville",
        fontStyle: "italic",
        fontSize: 3.0,
    } as FontConfig,
    "black-Ridi-normal-0_750": {
        color: colorSwatcher.black,
        fontFamily: "Ridi",
        fontStyle: "normal",
        fontSize: 0.75,
    } as FontConfig,
    "black-Ridi-normal-0_875": {
        color: colorSwatcher.black,
        fontFamily: "Ridi",
        fontStyle: "normal",
        fontSize: 0.875,
    } as FontConfig,
    "black-Ridi-normal-1_000": {
        color: colorSwatcher.black,
        fontFamily: "Ridi",
        fontStyle: "normal",
        fontSize: 1.0,
    } as FontConfig,
    "black-Ridi-normal-1_125": {
        color: colorSwatcher.black,
        fontFamily: "Ridi",
        fontStyle: "normal",
        fontSize: 1.125,
    } as FontConfig,
    "black-Ridi-normal-1_250": {
        color: colorSwatcher.black,
        fontFamily: "Ridi",
        fontStyle: "normal",
        fontSize: 1.25,
    } as FontConfig,
    "black-Ridi-normal-1_375": {
        color: colorSwatcher.black,
        fontFamily: "Ridi",
        fontStyle: "normal",
        fontSize: 1.375,
    } as FontConfig,
    "black-Ridi-normal-1_500": {
        color: colorSwatcher.black,
        fontFamily: "Ridi",
        fontStyle: "normal",
        fontSize: 1.5,
    } as FontConfig,
    "black-Ridi-normal-1_625": {
        color: colorSwatcher.black,
        fontFamily: "Ridi",
        fontStyle: "normal",
        fontSize: 1.625,
    } as FontConfig,
    "black-Ridi-normal-1_750": {
        color: colorSwatcher.black,
        fontFamily: "Ridi",
        fontStyle: "normal",
        fontSize: 1.75,
    } as FontConfig,
    "black-Ridi-normal-1_875": {
        color: colorSwatcher.black,
        fontFamily: "Ridi",
        fontStyle: "normal",
        fontSize: 1.875,
    } as FontConfig,
    "black-Ridi-normal-2_000": {
        color: colorSwatcher.black,
        fontFamily: "Ridi",
        fontStyle: "normal",
        fontSize: 2.0,
    } as FontConfig,
    "black-Ridi-normal-2_125": {
        color: colorSwatcher.black,
        fontFamily: "Ridi",
        fontStyle: "normal",
        fontSize: 2.125,
    } as FontConfig,
    "black-Ridi-normal-2_250": {
        color: colorSwatcher.black,
        fontFamily: "Ridi",
        fontStyle: "normal",
        fontSize: 2.25,
    } as FontConfig,
    "black-Ridi-normal-2_375": {
        color: colorSwatcher.black,
        fontFamily: "Ridi",
        fontStyle: "normal",
        fontSize: 2.375,
    } as FontConfig,
    "black-Ridi-normal-2_500": {
        color: colorSwatcher.black,
        fontFamily: "Ridi",
        fontStyle: "normal",
        fontSize: 2.5,
    } as FontConfig,
    "black-Ridi-normal-2_625": {
        color: colorSwatcher.black,
        fontFamily: "Ridi",
        fontStyle: "normal",
        fontSize: 2.625,
    } as FontConfig,
    "black-Ridi-normal-2_750": {
        color: colorSwatcher.black,
        fontFamily: "Ridi",
        fontStyle: "normal",
        fontSize: 2.75,
    } as FontConfig,
    "black-Ridi-normal-2_875": {
        color: colorSwatcher.black,
        fontFamily: "Ridi",
        fontStyle: "normal",
        fontSize: 2.875,
    } as FontConfig,
    "black-Ridi-normal-3_000": {
        color: colorSwatcher.black,
        fontFamily: "Ridi",
        fontStyle: "normal",
        fontSize: 3.0,
    } as FontConfig,
    "black-Ridi-italic-0_750": {
        color: colorSwatcher.black,
        fontFamily: "Ridi",
        fontStyle: "italic",
        fontSize: 0.75,
    } as FontConfig,
    "black-Ridi-italic-0_875": {
        color: colorSwatcher.black,
        fontFamily: "Ridi",
        fontStyle: "italic",
        fontSize: 0.875,
    } as FontConfig,
    "black-Ridi-italic-1_000": {
        color: colorSwatcher.black,
        fontFamily: "Ridi",
        fontStyle: "italic",
        fontSize: 1.0,
    } as FontConfig,
    "black-Ridi-italic-1_125": {
        color: colorSwatcher.black,
        fontFamily: "Ridi",
        fontStyle: "italic",
        fontSize: 1.125,
    } as FontConfig,
    "black-Ridi-italic-1_250": {
        color: colorSwatcher.black,
        fontFamily: "Ridi",
        fontStyle: "italic",
        fontSize: 1.25,
    } as FontConfig,
    "black-Ridi-italic-1_375": {
        color: colorSwatcher.black,
        fontFamily: "Ridi",
        fontStyle: "italic",
        fontSize: 1.375,
    } as FontConfig,
    "black-Ridi-italic-1_500": {
        color: colorSwatcher.black,
        fontFamily: "Ridi",
        fontStyle: "italic",
        fontSize: 1.5,
    } as FontConfig,
    "black-Ridi-italic-1_625": {
        color: colorSwatcher.black,
        fontFamily: "Ridi",
        fontStyle: "italic",
        fontSize: 1.625,
    } as FontConfig,
    "black-Ridi-italic-1_750": {
        color: colorSwatcher.black,
        fontFamily: "Ridi",
        fontStyle: "italic",
        fontSize: 1.75,
    } as FontConfig,
    "black-Ridi-italic-1_875": {
        color: colorSwatcher.black,
        fontFamily: "Ridi",
        fontStyle: "italic",
        fontSize: 1.875,
    } as FontConfig,
    "black-Ridi-italic-2_000": {
        color: colorSwatcher.black,
        fontFamily: "Ridi",
        fontStyle: "italic",
        fontSize: 2.0,
    } as FontConfig,
    "black-Ridi-italic-2_125": {
        color: colorSwatcher.black,
        fontFamily: "Ridi",
        fontStyle: "italic",
        fontSize: 2.125,
    } as FontConfig,
    "black-Ridi-italic-2_250": {
        color: colorSwatcher.black,
        fontFamily: "Ridi",
        fontStyle: "italic",
        fontSize: 2.25,
    } as FontConfig,
    "black-Ridi-italic-2_375": {
        color: colorSwatcher.black,
        fontFamily: "Ridi",
        fontStyle: "italic",
        fontSize: 2.375,
    } as FontConfig,
    "black-Ridi-italic-2_500": {
        color: colorSwatcher.black,
        fontFamily: "Ridi",
        fontStyle: "italic",
        fontSize: 2.5,
    } as FontConfig,
    "black-Ridi-italic-2_625": {
        color: colorSwatcher.black,
        fontFamily: "Ridi",
        fontStyle: "italic",
        fontSize: 2.625,
    } as FontConfig,
    "black-Ridi-italic-2_750": {
        color: colorSwatcher.black,
        fontFamily: "Ridi",
        fontStyle: "italic",
        fontSize: 2.75,
    } as FontConfig,
    "black-Ridi-italic-2_875": {
        color: colorSwatcher.black,
        fontFamily: "Ridi",
        fontStyle: "italic",
        fontSize: 2.875,
    } as FontConfig,
    "black-Ridi-italic-3_000": {
        color: colorSwatcher.black,
        fontFamily: "Ridi",
        fontStyle: "italic",
        fontSize: 3.0,
    } as FontConfig,
    "bodyBackground-Baskerville-normal-0_750": {
        color: colorSwatcher.bodyBackground,
        fontFamily: "Baskerville",
        fontStyle: "normal",
        fontSize: 0.75,
    } as FontConfig,
    "bodyBackground-Baskerville-normal-0_875": {
        color: colorSwatcher.bodyBackground,
        fontFamily: "Baskerville",
        fontStyle: "normal",
        fontSize: 0.875,
    } as FontConfig,
    "bodyBackground-Baskerville-normal-1_000": {
        color: colorSwatcher.bodyBackground,
        fontFamily: "Baskerville",
        fontStyle: "normal",
        fontSize: 1.0,
    } as FontConfig,
    "bodyBackground-Baskerville-normal-1_125": {
        color: colorSwatcher.bodyBackground,
        fontFamily: "Baskerville",
        fontStyle: "normal",
        fontSize: 1.125,
    } as FontConfig,
    "bodyBackground-Baskerville-normal-1_250": {
        color: colorSwatcher.bodyBackground,
        fontFamily: "Baskerville",
        fontStyle: "normal",
        fontSize: 1.25,
    } as FontConfig,
    "bodyBackground-Baskerville-normal-1_375": {
        color: colorSwatcher.bodyBackground,
        fontFamily: "Baskerville",
        fontStyle: "normal",
        fontSize: 1.375,
    } as FontConfig,
    "bodyBackground-Baskerville-normal-1_500": {
        color: colorSwatcher.bodyBackground,
        fontFamily: "Baskerville",
        fontStyle: "normal",
        fontSize: 1.5,
    } as FontConfig,
    "bodyBackground-Baskerville-normal-1_625": {
        color: colorSwatcher.bodyBackground,
        fontFamily: "Baskerville",
        fontStyle: "normal",
        fontSize: 1.625,
    } as FontConfig,
    "bodyBackground-Baskerville-normal-1_750": {
        color: colorSwatcher.bodyBackground,
        fontFamily: "Baskerville",
        fontStyle: "normal",
        fontSize: 1.75,
    } as FontConfig,
    "bodyBackground-Baskerville-normal-1_875": {
        color: colorSwatcher.bodyBackground,
        fontFamily: "Baskerville",
        fontStyle: "normal",
        fontSize: 1.875,
    } as FontConfig,
    "bodyBackground-Baskerville-normal-2_000": {
        color: colorSwatcher.bodyBackground,
        fontFamily: "Baskerville",
        fontStyle: "normal",
        fontSize: 2.0,
    } as FontConfig,
    "bodyBackground-Baskerville-normal-2_125": {
        color: colorSwatcher.bodyBackground,
        fontFamily: "Baskerville",
        fontStyle: "normal",
        fontSize: 2.125,
    } as FontConfig,
    "bodyBackground-Baskerville-normal-2_250": {
        color: colorSwatcher.bodyBackground,
        fontFamily: "Baskerville",
        fontStyle: "normal",
        fontSize: 2.25,
    } as FontConfig,
    "bodyBackground-Baskerville-normal-2_375": {
        color: colorSwatcher.bodyBackground,
        fontFamily: "Baskerville",
        fontStyle: "normal",
        fontSize: 2.375,
    } as FontConfig,
    "bodyBackground-Baskerville-normal-2_500": {
        color: colorSwatcher.bodyBackground,
        fontFamily: "Baskerville",
        fontStyle: "normal",
        fontSize: 2.5,
    } as FontConfig,
    "bodyBackground-Baskerville-normal-2_625": {
        color: colorSwatcher.bodyBackground,
        fontFamily: "Baskerville",
        fontStyle: "normal",
        fontSize: 2.625,
    } as FontConfig,
    "bodyBackground-Baskerville-normal-2_750": {
        color: colorSwatcher.bodyBackground,
        fontFamily: "Baskerville",
        fontStyle: "normal",
        fontSize: 2.75,
    } as FontConfig,
    "bodyBackground-Baskerville-normal-2_875": {
        color: colorSwatcher.bodyBackground,
        fontFamily: "Baskerville",
        fontStyle: "normal",
        fontSize: 2.875,
    } as FontConfig,
    "bodyBackground-Baskerville-normal-3_000": {
        color: colorSwatcher.bodyBackground,
        fontFamily: "Baskerville",
        fontStyle: "normal",
        fontSize: 3.0,
    } as FontConfig,
    "bodyBackground-Baskerville-italic-0_750": {
        color: colorSwatcher.bodyBackground,
        fontFamily: "Baskerville",
        fontStyle: "italic",
        fontSize: 0.75,
    } as FontConfig,
    "bodyBackground-Baskerville-italic-0_875": {
        color: colorSwatcher.bodyBackground,
        fontFamily: "Baskerville",
        fontStyle: "italic",
        fontSize: 0.875,
    } as FontConfig,
    "bodyBackground-Baskerville-italic-1_000": {
        color: colorSwatcher.bodyBackground,
        fontFamily: "Baskerville",
        fontStyle: "italic",
        fontSize: 1.0,
    } as FontConfig,
    "bodyBackground-Baskerville-italic-1_125": {
        color: colorSwatcher.bodyBackground,
        fontFamily: "Baskerville",
        fontStyle: "italic",
        fontSize: 1.125,
    } as FontConfig,
    "bodyBackground-Baskerville-italic-1_250": {
        color: colorSwatcher.bodyBackground,
        fontFamily: "Baskerville",
        fontStyle: "italic",
        fontSize: 1.25,
    } as FontConfig,
    "bodyBackground-Baskerville-italic-1_375": {
        color: colorSwatcher.bodyBackground,
        fontFamily: "Baskerville",
        fontStyle: "italic",
        fontSize: 1.375,
    } as FontConfig,
    "bodyBackground-Baskerville-italic-1_500": {
        color: colorSwatcher.bodyBackground,
        fontFamily: "Baskerville",
        fontStyle: "italic",
        fontSize: 1.5,
    } as FontConfig,
    "bodyBackground-Baskerville-italic-1_625": {
        color: colorSwatcher.bodyBackground,
        fontFamily: "Baskerville",
        fontStyle: "italic",
        fontSize: 1.625,
    } as FontConfig,
    "bodyBackground-Baskerville-italic-1_750": {
        color: colorSwatcher.bodyBackground,
        fontFamily: "Baskerville",
        fontStyle: "italic",
        fontSize: 1.75,
    } as FontConfig,
    "bodyBackground-Baskerville-italic-1_875": {
        color: colorSwatcher.bodyBackground,
        fontFamily: "Baskerville",
        fontStyle: "italic",
        fontSize: 1.875,
    } as FontConfig,
    "bodyBackground-Baskerville-italic-2_000": {
        color: colorSwatcher.bodyBackground,
        fontFamily: "Baskerville",
        fontStyle: "italic",
        fontSize: 2.0,
    } as FontConfig,
    "bodyBackground-Baskerville-italic-2_125": {
        color: colorSwatcher.bodyBackground,
        fontFamily: "Baskerville",
        fontStyle: "italic",
        fontSize: 2.125,
    } as FontConfig,
    "bodyBackground-Baskerville-italic-2_250": {
        color: colorSwatcher.bodyBackground,
        fontFamily: "Baskerville",
        fontStyle: "italic",
        fontSize: 2.25,
    } as FontConfig,
    "bodyBackground-Baskerville-italic-2_375": {
        color: colorSwatcher.bodyBackground,
        fontFamily: "Baskerville",
        fontStyle: "italic",
        fontSize: 2.375,
    } as FontConfig,
    "bodyBackground-Baskerville-italic-2_500": {
        color: colorSwatcher.bodyBackground,
        fontFamily: "Baskerville",
        fontStyle: "italic",
        fontSize: 2.5,
    } as FontConfig,
    "bodyBackground-Baskerville-italic-2_625": {
        color: colorSwatcher.bodyBackground,
        fontFamily: "Baskerville",
        fontStyle: "italic",
        fontSize: 2.625,
    } as FontConfig,
    "bodyBackground-Baskerville-italic-2_750": {
        color: colorSwatcher.bodyBackground,
        fontFamily: "Baskerville",
        fontStyle: "italic",
        fontSize: 2.75,
    } as FontConfig,
    "bodyBackground-Baskerville-italic-2_875": {
        color: colorSwatcher.bodyBackground,
        fontFamily: "Baskerville",
        fontStyle: "italic",
        fontSize: 2.875,
    } as FontConfig,
    "bodyBackground-Baskerville-italic-3_000": {
        color: colorSwatcher.bodyBackground,
        fontFamily: "Baskerville",
        fontStyle: "italic",
        fontSize: 3.0,
    } as FontConfig,
    "bodyBackground-Ridi-normal-0_750": {
        color: colorSwatcher.bodyBackground,
        fontFamily: "Ridi",
        fontStyle: "normal",
        fontSize: 0.75,
    } as FontConfig,
    "bodyBackground-Ridi-normal-0_875": {
        color: colorSwatcher.bodyBackground,
        fontFamily: "Ridi",
        fontStyle: "normal",
        fontSize: 0.875,
    } as FontConfig,
    "bodyBackground-Ridi-normal-1_000": {
        color: colorSwatcher.bodyBackground,
        fontFamily: "Ridi",
        fontStyle: "normal",
        fontSize: 1.0,
    } as FontConfig,
    "bodyBackground-Ridi-normal-1_125": {
        color: colorSwatcher.bodyBackground,
        fontFamily: "Ridi",
        fontStyle: "normal",
        fontSize: 1.125,
    } as FontConfig,
    "bodyBackground-Ridi-normal-1_250": {
        color: colorSwatcher.bodyBackground,
        fontFamily: "Ridi",
        fontStyle: "normal",
        fontSize: 1.25,
    } as FontConfig,
    "bodyBackground-Ridi-normal-1_375": {
        color: colorSwatcher.bodyBackground,
        fontFamily: "Ridi",
        fontStyle: "normal",
        fontSize: 1.375,
    } as FontConfig,
    "bodyBackground-Ridi-normal-1_500": {
        color: colorSwatcher.bodyBackground,
        fontFamily: "Ridi",
        fontStyle: "normal",
        fontSize: 1.5,
    } as FontConfig,
    "bodyBackground-Ridi-normal-1_625": {
        color: colorSwatcher.bodyBackground,
        fontFamily: "Ridi",
        fontStyle: "normal",
        fontSize: 1.625,
    } as FontConfig,
    "bodyBackground-Ridi-normal-1_750": {
        color: colorSwatcher.bodyBackground,
        fontFamily: "Ridi",
        fontStyle: "normal",
        fontSize: 1.75,
    } as FontConfig,
    "bodyBackground-Ridi-normal-1_875": {
        color: colorSwatcher.bodyBackground,
        fontFamily: "Ridi",
        fontStyle: "normal",
        fontSize: 1.875,
    } as FontConfig,
    "bodyBackground-Ridi-normal-2_000": {
        color: colorSwatcher.bodyBackground,
        fontFamily: "Ridi",
        fontStyle: "normal",
        fontSize: 2.0,
    } as FontConfig,
    "bodyBackground-Ridi-normal-2_125": {
        color: colorSwatcher.bodyBackground,
        fontFamily: "Ridi",
        fontStyle: "normal",
        fontSize: 2.125,
    } as FontConfig,
    "bodyBackground-Ridi-normal-2_250": {
        color: colorSwatcher.bodyBackground,
        fontFamily: "Ridi",
        fontStyle: "normal",
        fontSize: 2.25,
    } as FontConfig,
    "bodyBackground-Ridi-normal-2_375": {
        color: colorSwatcher.bodyBackground,
        fontFamily: "Ridi",
        fontStyle: "normal",
        fontSize: 2.375,
    } as FontConfig,
    "bodyBackground-Ridi-normal-2_500": {
        color: colorSwatcher.bodyBackground,
        fontFamily: "Ridi",
        fontStyle: "normal",
        fontSize: 2.5,
    } as FontConfig,
    "bodyBackground-Ridi-normal-2_625": {
        color: colorSwatcher.bodyBackground,
        fontFamily: "Ridi",
        fontStyle: "normal",
        fontSize: 2.625,
    } as FontConfig,
    "bodyBackground-Ridi-normal-2_750": {
        color: colorSwatcher.bodyBackground,
        fontFamily: "Ridi",
        fontStyle: "normal",
        fontSize: 2.75,
    } as FontConfig,
    "bodyBackground-Ridi-normal-2_875": {
        color: colorSwatcher.bodyBackground,
        fontFamily: "Ridi",
        fontStyle: "normal",
        fontSize: 2.875,
    } as FontConfig,
    "bodyBackground-Ridi-normal-3_000": {
        color: colorSwatcher.bodyBackground,
        fontFamily: "Ridi",
        fontStyle: "normal",
        fontSize: 3.0,
    } as FontConfig,
    "bodyBackground-Ridi-italic-0_750": {
        color: colorSwatcher.bodyBackground,
        fontFamily: "Ridi",
        fontStyle: "italic",
        fontSize: 0.75,
    } as FontConfig,
    "bodyBackground-Ridi-italic-0_875": {
        color: colorSwatcher.bodyBackground,
        fontFamily: "Ridi",
        fontStyle: "italic",
        fontSize: 0.875,
    } as FontConfig,
    "bodyBackground-Ridi-italic-1_000": {
        color: colorSwatcher.bodyBackground,
        fontFamily: "Ridi",
        fontStyle: "italic",
        fontSize: 1.0,
    } as FontConfig,
    "bodyBackground-Ridi-italic-1_125": {
        color: colorSwatcher.bodyBackground,
        fontFamily: "Ridi",
        fontStyle: "italic",
        fontSize: 1.125,
    } as FontConfig,
    "bodyBackground-Ridi-italic-1_250": {
        color: colorSwatcher.bodyBackground,
        fontFamily: "Ridi",
        fontStyle: "italic",
        fontSize: 1.25,
    } as FontConfig,
    "bodyBackground-Ridi-italic-1_375": {
        color: colorSwatcher.bodyBackground,
        fontFamily: "Ridi",
        fontStyle: "italic",
        fontSize: 1.375,
    } as FontConfig,
    "bodyBackground-Ridi-italic-1_500": {
        color: colorSwatcher.bodyBackground,
        fontFamily: "Ridi",
        fontStyle: "italic",
        fontSize: 1.5,
    } as FontConfig,
    "bodyBackground-Ridi-italic-1_625": {
        color: colorSwatcher.bodyBackground,
        fontFamily: "Ridi",
        fontStyle: "italic",
        fontSize: 1.625,
    } as FontConfig,
    "bodyBackground-Ridi-italic-1_750": {
        color: colorSwatcher.bodyBackground,
        fontFamily: "Ridi",
        fontStyle: "italic",
        fontSize: 1.75,
    } as FontConfig,
    "bodyBackground-Ridi-italic-1_875": {
        color: colorSwatcher.bodyBackground,
        fontFamily: "Ridi",
        fontStyle: "italic",
        fontSize: 1.875,
    } as FontConfig,
    "bodyBackground-Ridi-italic-2_000": {
        color: colorSwatcher.bodyBackground,
        fontFamily: "Ridi",
        fontStyle: "italic",
        fontSize: 2.0,
    } as FontConfig,
    "bodyBackground-Ridi-italic-2_125": {
        color: colorSwatcher.bodyBackground,
        fontFamily: "Ridi",
        fontStyle: "italic",
        fontSize: 2.125,
    } as FontConfig,
    "bodyBackground-Ridi-italic-2_250": {
        color: colorSwatcher.bodyBackground,
        fontFamily: "Ridi",
        fontStyle: "italic",
        fontSize: 2.25,
    } as FontConfig,
    "bodyBackground-Ridi-italic-2_375": {
        color: colorSwatcher.bodyBackground,
        fontFamily: "Ridi",
        fontStyle: "italic",
        fontSize: 2.375,
    } as FontConfig,
    "bodyBackground-Ridi-italic-2_500": {
        color: colorSwatcher.bodyBackground,
        fontFamily: "Ridi",
        fontStyle: "italic",
        fontSize: 2.5,
    } as FontConfig,
    "bodyBackground-Ridi-italic-2_625": {
        color: colorSwatcher.bodyBackground,
        fontFamily: "Ridi",
        fontStyle: "italic",
        fontSize: 2.625,
    } as FontConfig,
    "bodyBackground-Ridi-italic-2_750": {
        color: colorSwatcher.bodyBackground,
        fontFamily: "Ridi",
        fontStyle: "italic",
        fontSize: 2.75,
    } as FontConfig,
    "bodyBackground-Ridi-italic-2_875": {
        color: colorSwatcher.bodyBackground,
        fontFamily: "Ridi",
        fontStyle: "italic",
        fontSize: 2.875,
    } as FontConfig,
    "bodyBackground-Ridi-italic-3_000": {
        color: colorSwatcher.bodyBackground,
        fontFamily: "Ridi",
        fontStyle: "italic",
        fontSize: 3.0,
    } as FontConfig,
    "textColorHighlight-Baskerville-normal-0_750": {
        color: colorSwatcher.textColorHighlight,
        fontFamily: "Baskerville",
        fontStyle: "normal",
        fontSize: 0.75,
    } as FontConfig,
    "textColorHighlight-Baskerville-normal-0_875": {
        color: colorSwatcher.textColorHighlight,
        fontFamily: "Baskerville",
        fontStyle: "normal",
        fontSize: 0.875,
    } as FontConfig,
    "textColorHighlight-Baskerville-normal-1_000": {
        color: colorSwatcher.textColorHighlight,
        fontFamily: "Baskerville",
        fontStyle: "normal",
        fontSize: 1.0,
    } as FontConfig,
    "textColorHighlight-Baskerville-normal-1_125": {
        color: colorSwatcher.textColorHighlight,
        fontFamily: "Baskerville",
        fontStyle: "normal",
        fontSize: 1.125,
    } as FontConfig,
    "textColorHighlight-Baskerville-normal-1_250": {
        color: colorSwatcher.textColorHighlight,
        fontFamily: "Baskerville",
        fontStyle: "normal",
        fontSize: 1.25,
    } as FontConfig,
    "textColorHighlight-Baskerville-normal-1_375": {
        color: colorSwatcher.textColorHighlight,
        fontFamily: "Baskerville",
        fontStyle: "normal",
        fontSize: 1.375,
    } as FontConfig,
    "textColorHighlight-Baskerville-normal-1_500": {
        color: colorSwatcher.textColorHighlight,
        fontFamily: "Baskerville",
        fontStyle: "normal",
        fontSize: 1.5,
    } as FontConfig,
    "textColorHighlight-Baskerville-normal-1_625": {
        color: colorSwatcher.textColorHighlight,
        fontFamily: "Baskerville",
        fontStyle: "normal",
        fontSize: 1.625,
    } as FontConfig,
    "textColorHighlight-Baskerville-normal-1_750": {
        color: colorSwatcher.textColorHighlight,
        fontFamily: "Baskerville",
        fontStyle: "normal",
        fontSize: 1.75,
    } as FontConfig,
    "textColorHighlight-Baskerville-normal-1_875": {
        color: colorSwatcher.textColorHighlight,
        fontFamily: "Baskerville",
        fontStyle: "normal",
        fontSize: 1.875,
    } as FontConfig,
    "textColorHighlight-Baskerville-normal-2_000": {
        color: colorSwatcher.textColorHighlight,
        fontFamily: "Baskerville",
        fontStyle: "normal",
        fontSize: 2.0,
    } as FontConfig,
    "textColorHighlight-Baskerville-normal-2_125": {
        color: colorSwatcher.textColorHighlight,
        fontFamily: "Baskerville",
        fontStyle: "normal",
        fontSize: 2.125,
    } as FontConfig,
    "textColorHighlight-Baskerville-normal-2_250": {
        color: colorSwatcher.textColorHighlight,
        fontFamily: "Baskerville",
        fontStyle: "normal",
        fontSize: 2.25,
    } as FontConfig,
    "textColorHighlight-Baskerville-normal-2_375": {
        color: colorSwatcher.textColorHighlight,
        fontFamily: "Baskerville",
        fontStyle: "normal",
        fontSize: 2.375,
    } as FontConfig,
    "textColorHighlight-Baskerville-normal-2_500": {
        color: colorSwatcher.textColorHighlight,
        fontFamily: "Baskerville",
        fontStyle: "normal",
        fontSize: 2.5,
    } as FontConfig,
    "textColorHighlight-Baskerville-normal-2_625": {
        color: colorSwatcher.textColorHighlight,
        fontFamily: "Baskerville",
        fontStyle: "normal",
        fontSize: 2.625,
    } as FontConfig,
    "textColorHighlight-Baskerville-normal-2_750": {
        color: colorSwatcher.textColorHighlight,
        fontFamily: "Baskerville",
        fontStyle: "normal",
        fontSize: 2.75,
    } as FontConfig,
    "textColorHighlight-Baskerville-normal-2_875": {
        color: colorSwatcher.textColorHighlight,
        fontFamily: "Baskerville",
        fontStyle: "normal",
        fontSize: 2.875,
    } as FontConfig,
    "textColorHighlight-Baskerville-normal-3_000": {
        color: colorSwatcher.textColorHighlight,
        fontFamily: "Baskerville",
        fontStyle: "normal",
        fontSize: 3.0,
    } as FontConfig,
    "textColorHighlight-Baskerville-italic-0_750": {
        color: colorSwatcher.textColorHighlight,
        fontFamily: "Baskerville",
        fontStyle: "italic",
        fontSize: 0.75,
    } as FontConfig,
    "textColorHighlight-Baskerville-italic-0_875": {
        color: colorSwatcher.textColorHighlight,
        fontFamily: "Baskerville",
        fontStyle: "italic",
        fontSize: 0.875,
    } as FontConfig,
    "textColorHighlight-Baskerville-italic-1_000": {
        color: colorSwatcher.textColorHighlight,
        fontFamily: "Baskerville",
        fontStyle: "italic",
        fontSize: 1.0,
    } as FontConfig,
    "textColorHighlight-Baskerville-italic-1_125": {
        color: colorSwatcher.textColorHighlight,
        fontFamily: "Baskerville",
        fontStyle: "italic",
        fontSize: 1.125,
    } as FontConfig,
    "textColorHighlight-Baskerville-italic-1_250": {
        color: colorSwatcher.textColorHighlight,
        fontFamily: "Baskerville",
        fontStyle: "italic",
        fontSize: 1.25,
    } as FontConfig,
    "textColorHighlight-Baskerville-italic-1_375": {
        color: colorSwatcher.textColorHighlight,
        fontFamily: "Baskerville",
        fontStyle: "italic",
        fontSize: 1.375,
    } as FontConfig,
    "textColorHighlight-Baskerville-italic-1_500": {
        color: colorSwatcher.textColorHighlight,
        fontFamily: "Baskerville",
        fontStyle: "italic",
        fontSize: 1.5,
    } as FontConfig,
    "textColorHighlight-Baskerville-italic-1_625": {
        color: colorSwatcher.textColorHighlight,
        fontFamily: "Baskerville",
        fontStyle: "italic",
        fontSize: 1.625,
    } as FontConfig,
    "textColorHighlight-Baskerville-italic-1_750": {
        color: colorSwatcher.textColorHighlight,
        fontFamily: "Baskerville",
        fontStyle: "italic",
        fontSize: 1.75,
    } as FontConfig,
    "textColorHighlight-Baskerville-italic-1_875": {
        color: colorSwatcher.textColorHighlight,
        fontFamily: "Baskerville",
        fontStyle: "italic",
        fontSize: 1.875,
    } as FontConfig,
    "textColorHighlight-Baskerville-italic-2_000": {
        color: colorSwatcher.textColorHighlight,
        fontFamily: "Baskerville",
        fontStyle: "italic",
        fontSize: 2.0,
    } as FontConfig,
    "textColorHighlight-Baskerville-italic-2_125": {
        color: colorSwatcher.textColorHighlight,
        fontFamily: "Baskerville",
        fontStyle: "italic",
        fontSize: 2.125,
    } as FontConfig,
    "textColorHighlight-Baskerville-italic-2_250": {
        color: colorSwatcher.textColorHighlight,
        fontFamily: "Baskerville",
        fontStyle: "italic",
        fontSize: 2.25,
    } as FontConfig,
    "textColorHighlight-Baskerville-italic-2_375": {
        color: colorSwatcher.textColorHighlight,
        fontFamily: "Baskerville",
        fontStyle: "italic",
        fontSize: 2.375,
    } as FontConfig,
    "textColorHighlight-Baskerville-italic-2_500": {
        color: colorSwatcher.textColorHighlight,
        fontFamily: "Baskerville",
        fontStyle: "italic",
        fontSize: 2.5,
    } as FontConfig,
    "textColorHighlight-Baskerville-italic-2_625": {
        color: colorSwatcher.textColorHighlight,
        fontFamily: "Baskerville",
        fontStyle: "italic",
        fontSize: 2.625,
    } as FontConfig,
    "textColorHighlight-Baskerville-italic-2_750": {
        color: colorSwatcher.textColorHighlight,
        fontFamily: "Baskerville",
        fontStyle: "italic",
        fontSize: 2.75,
    } as FontConfig,
    "textColorHighlight-Baskerville-italic-2_875": {
        color: colorSwatcher.textColorHighlight,
        fontFamily: "Baskerville",
        fontStyle: "italic",
        fontSize: 2.875,
    } as FontConfig,
    "textColorHighlight-Baskerville-italic-3_000": {
        color: colorSwatcher.textColorHighlight,
        fontFamily: "Baskerville",
        fontStyle: "italic",
        fontSize: 3.0,
    } as FontConfig,
    "textColorHighlight-Ridi-normal-0_750": {
        color: colorSwatcher.textColorHighlight,
        fontFamily: "Ridi",
        fontStyle: "normal",
        fontSize: 0.75,
    } as FontConfig,
    "textColorHighlight-Ridi-normal-0_875": {
        color: colorSwatcher.textColorHighlight,
        fontFamily: "Ridi",
        fontStyle: "normal",
        fontSize: 0.875,
    } as FontConfig,
    "textColorHighlight-Ridi-normal-1_000": {
        color: colorSwatcher.textColorHighlight,
        fontFamily: "Ridi",
        fontStyle: "normal",
        fontSize: 1.0,
    } as FontConfig,
    "textColorHighlight-Ridi-normal-1_125": {
        color: colorSwatcher.textColorHighlight,
        fontFamily: "Ridi",
        fontStyle: "normal",
        fontSize: 1.125,
    } as FontConfig,
    "textColorHighlight-Ridi-normal-1_250": {
        color: colorSwatcher.textColorHighlight,
        fontFamily: "Ridi",
        fontStyle: "normal",
        fontSize: 1.25,
    } as FontConfig,
    "textColorHighlight-Ridi-normal-1_375": {
        color: colorSwatcher.textColorHighlight,
        fontFamily: "Ridi",
        fontStyle: "normal",
        fontSize: 1.375,
    } as FontConfig,
    "textColorHighlight-Ridi-normal-1_500": {
        color: colorSwatcher.textColorHighlight,
        fontFamily: "Ridi",
        fontStyle: "normal",
        fontSize: 1.5,
    } as FontConfig,
    "textColorHighlight-Ridi-normal-1_625": {
        color: colorSwatcher.textColorHighlight,
        fontFamily: "Ridi",
        fontStyle: "normal",
        fontSize: 1.625,
    } as FontConfig,
    "textColorHighlight-Ridi-normal-1_750": {
        color: colorSwatcher.textColorHighlight,
        fontFamily: "Ridi",
        fontStyle: "normal",
        fontSize: 1.75,
    } as FontConfig,
    "textColorHighlight-Ridi-normal-1_875": {
        color: colorSwatcher.textColorHighlight,
        fontFamily: "Ridi",
        fontStyle: "normal",
        fontSize: 1.875,
    } as FontConfig,
    "textColorHighlight-Ridi-normal-2_000": {
        color: colorSwatcher.textColorHighlight,
        fontFamily: "Ridi",
        fontStyle: "normal",
        fontSize: 2.0,
    } as FontConfig,
    "textColorHighlight-Ridi-normal-2_125": {
        color: colorSwatcher.textColorHighlight,
        fontFamily: "Ridi",
        fontStyle: "normal",
        fontSize: 2.125,
    } as FontConfig,
    "textColorHighlight-Ridi-normal-2_250": {
        color: colorSwatcher.textColorHighlight,
        fontFamily: "Ridi",
        fontStyle: "normal",
        fontSize: 2.25,
    } as FontConfig,
    "textColorHighlight-Ridi-normal-2_375": {
        color: colorSwatcher.textColorHighlight,
        fontFamily: "Ridi",
        fontStyle: "normal",
        fontSize: 2.375,
    } as FontConfig,
    "textColorHighlight-Ridi-normal-2_500": {
        color: colorSwatcher.textColorHighlight,
        fontFamily: "Ridi",
        fontStyle: "normal",
        fontSize: 2.5,
    } as FontConfig,
    "textColorHighlight-Ridi-normal-2_625": {
        color: colorSwatcher.textColorHighlight,
        fontFamily: "Ridi",
        fontStyle: "normal",
        fontSize: 2.625,
    } as FontConfig,
    "textColorHighlight-Ridi-normal-2_750": {
        color: colorSwatcher.textColorHighlight,
        fontFamily: "Ridi",
        fontStyle: "normal",
        fontSize: 2.75,
    } as FontConfig,
    "textColorHighlight-Ridi-normal-2_875": {
        color: colorSwatcher.textColorHighlight,
        fontFamily: "Ridi",
        fontStyle: "normal",
        fontSize: 2.875,
    } as FontConfig,
    "textColorHighlight-Ridi-normal-3_000": {
        color: colorSwatcher.textColorHighlight,
        fontFamily: "Ridi",
        fontStyle: "normal",
        fontSize: 3.0,
    } as FontConfig,
    "textColorHighlight-Ridi-italic-0_750": {
        color: colorSwatcher.textColorHighlight,
        fontFamily: "Ridi",
        fontStyle: "italic",
        fontSize: 0.75,
    } as FontConfig,
    "textColorHighlight-Ridi-italic-0_875": {
        color: colorSwatcher.textColorHighlight,
        fontFamily: "Ridi",
        fontStyle: "italic",
        fontSize: 0.875,
    } as FontConfig,
    "textColorHighlight-Ridi-italic-1_000": {
        color: colorSwatcher.textColorHighlight,
        fontFamily: "Ridi",
        fontStyle: "italic",
        fontSize: 1.0,
    } as FontConfig,
    "textColorHighlight-Ridi-italic-1_125": {
        color: colorSwatcher.textColorHighlight,
        fontFamily: "Ridi",
        fontStyle: "italic",
        fontSize: 1.125,
    } as FontConfig,
    "textColorHighlight-Ridi-italic-1_250": {
        color: colorSwatcher.textColorHighlight,
        fontFamily: "Ridi",
        fontStyle: "italic",
        fontSize: 1.25,
    } as FontConfig,
    "textColorHighlight-Ridi-italic-1_375": {
        color: colorSwatcher.textColorHighlight,
        fontFamily: "Ridi",
        fontStyle: "italic",
        fontSize: 1.375,
    } as FontConfig,
    "textColorHighlight-Ridi-italic-1_500": {
        color: colorSwatcher.textColorHighlight,
        fontFamily: "Ridi",
        fontStyle: "italic",
        fontSize: 1.5,
    } as FontConfig,
    "textColorHighlight-Ridi-italic-1_625": {
        color: colorSwatcher.textColorHighlight,
        fontFamily: "Ridi",
        fontStyle: "italic",
        fontSize: 1.625,
    } as FontConfig,
    "textColorHighlight-Ridi-italic-1_750": {
        color: colorSwatcher.textColorHighlight,
        fontFamily: "Ridi",
        fontStyle: "italic",
        fontSize: 1.75,
    } as FontConfig,
    "textColorHighlight-Ridi-italic-1_875": {
        color: colorSwatcher.textColorHighlight,
        fontFamily: "Ridi",
        fontStyle: "italic",
        fontSize: 1.875,
    } as FontConfig,
    "textColorHighlight-Ridi-italic-2_000": {
        color: colorSwatcher.textColorHighlight,
        fontFamily: "Ridi",
        fontStyle: "italic",
        fontSize: 2.0,
    } as FontConfig,
    "textColorHighlight-Ridi-italic-2_125": {
        color: colorSwatcher.textColorHighlight,
        fontFamily: "Ridi",
        fontStyle: "italic",
        fontSize: 2.125,
    } as FontConfig,
    "textColorHighlight-Ridi-italic-2_250": {
        color: colorSwatcher.textColorHighlight,
        fontFamily: "Ridi",
        fontStyle: "italic",
        fontSize: 2.25,
    } as FontConfig,
    "textColorHighlight-Ridi-italic-2_375": {
        color: colorSwatcher.textColorHighlight,
        fontFamily: "Ridi",
        fontStyle: "italic",
        fontSize: 2.375,
    } as FontConfig,
    "textColorHighlight-Ridi-italic-2_500": {
        color: colorSwatcher.textColorHighlight,
        fontFamily: "Ridi",
        fontStyle: "italic",
        fontSize: 2.5,
    } as FontConfig,
    "textColorHighlight-Ridi-italic-2_625": {
        color: colorSwatcher.textColorHighlight,
        fontFamily: "Ridi",
        fontStyle: "italic",
        fontSize: 2.625,
    } as FontConfig,
    "textColorHighlight-Ridi-italic-2_750": {
        color: colorSwatcher.textColorHighlight,
        fontFamily: "Ridi",
        fontStyle: "italic",
        fontSize: 2.75,
    } as FontConfig,
    "textColorHighlight-Ridi-italic-2_875": {
        color: colorSwatcher.textColorHighlight,
        fontFamily: "Ridi",
        fontStyle: "italic",
        fontSize: 2.875,
    } as FontConfig,
    "textColorHighlight-Ridi-italic-3_000": {
        color: colorSwatcher.textColorHighlight,
        fontFamily: "Ridi",
        fontStyle: "italic",
        fontSize: 3.0,
    } as FontConfig,
    "textColorHighlightDimmed-Baskerville-normal-0_750": {
        color: colorSwatcher.textColorHighlightDimmed,
        fontFamily: "Baskerville",
        fontStyle: "normal",
        fontSize: 0.75,
    } as FontConfig,
    "textColorHighlightDimmed-Baskerville-normal-0_875": {
        color: colorSwatcher.textColorHighlightDimmed,
        fontFamily: "Baskerville",
        fontStyle: "normal",
        fontSize: 0.875,
    } as FontConfig,
    "textColorHighlightDimmed-Baskerville-normal-1_000": {
        color: colorSwatcher.textColorHighlightDimmed,
        fontFamily: "Baskerville",
        fontStyle: "normal",
        fontSize: 1.0,
    } as FontConfig,
    "textColorHighlightDimmed-Baskerville-normal-1_125": {
        color: colorSwatcher.textColorHighlightDimmed,
        fontFamily: "Baskerville",
        fontStyle: "normal",
        fontSize: 1.125,
    } as FontConfig,
    "textColorHighlightDimmed-Baskerville-normal-1_250": {
        color: colorSwatcher.textColorHighlightDimmed,
        fontFamily: "Baskerville",
        fontStyle: "normal",
        fontSize: 1.25,
    } as FontConfig,
    "textColorHighlightDimmed-Baskerville-normal-1_375": {
        color: colorSwatcher.textColorHighlightDimmed,
        fontFamily: "Baskerville",
        fontStyle: "normal",
        fontSize: 1.375,
    } as FontConfig,
    "textColorHighlightDimmed-Baskerville-normal-1_500": {
        color: colorSwatcher.textColorHighlightDimmed,
        fontFamily: "Baskerville",
        fontStyle: "normal",
        fontSize: 1.5,
    } as FontConfig,
    "textColorHighlightDimmed-Baskerville-normal-1_625": {
        color: colorSwatcher.textColorHighlightDimmed,
        fontFamily: "Baskerville",
        fontStyle: "normal",
        fontSize: 1.625,
    } as FontConfig,
    "textColorHighlightDimmed-Baskerville-normal-1_750": {
        color: colorSwatcher.textColorHighlightDimmed,
        fontFamily: "Baskerville",
        fontStyle: "normal",
        fontSize: 1.75,
    } as FontConfig,
    "textColorHighlightDimmed-Baskerville-normal-1_875": {
        color: colorSwatcher.textColorHighlightDimmed,
        fontFamily: "Baskerville",
        fontStyle: "normal",
        fontSize: 1.875,
    } as FontConfig,
    "textColorHighlightDimmed-Baskerville-normal-2_000": {
        color: colorSwatcher.textColorHighlightDimmed,
        fontFamily: "Baskerville",
        fontStyle: "normal",
        fontSize: 2.0,
    } as FontConfig,
    "textColorHighlightDimmed-Baskerville-normal-2_125": {
        color: colorSwatcher.textColorHighlightDimmed,
        fontFamily: "Baskerville",
        fontStyle: "normal",
        fontSize: 2.125,
    } as FontConfig,
    "textColorHighlightDimmed-Baskerville-normal-2_250": {
        color: colorSwatcher.textColorHighlightDimmed,
        fontFamily: "Baskerville",
        fontStyle: "normal",
        fontSize: 2.25,
    } as FontConfig,
    "textColorHighlightDimmed-Baskerville-normal-2_375": {
        color: colorSwatcher.textColorHighlightDimmed,
        fontFamily: "Baskerville",
        fontStyle: "normal",
        fontSize: 2.375,
    } as FontConfig,
    "textColorHighlightDimmed-Baskerville-normal-2_500": {
        color: colorSwatcher.textColorHighlightDimmed,
        fontFamily: "Baskerville",
        fontStyle: "normal",
        fontSize: 2.5,
    } as FontConfig,
    "textColorHighlightDimmed-Baskerville-normal-2_625": {
        color: colorSwatcher.textColorHighlightDimmed,
        fontFamily: "Baskerville",
        fontStyle: "normal",
        fontSize: 2.625,
    } as FontConfig,
    "textColorHighlightDimmed-Baskerville-normal-2_750": {
        color: colorSwatcher.textColorHighlightDimmed,
        fontFamily: "Baskerville",
        fontStyle: "normal",
        fontSize: 2.75,
    } as FontConfig,
    "textColorHighlightDimmed-Baskerville-normal-2_875": {
        color: colorSwatcher.textColorHighlightDimmed,
        fontFamily: "Baskerville",
        fontStyle: "normal",
        fontSize: 2.875,
    } as FontConfig,
    "textColorHighlightDimmed-Baskerville-normal-3_000": {
        color: colorSwatcher.textColorHighlightDimmed,
        fontFamily: "Baskerville",
        fontStyle: "normal",
        fontSize: 3.0,
    } as FontConfig,
    "textColorHighlightDimmed-Baskerville-italic-0_750": {
        color: colorSwatcher.textColorHighlightDimmed,
        fontFamily: "Baskerville",
        fontStyle: "italic",
        fontSize: 0.75,
    } as FontConfig,
    "textColorHighlightDimmed-Baskerville-italic-0_875": {
        color: colorSwatcher.textColorHighlightDimmed,
        fontFamily: "Baskerville",
        fontStyle: "italic",
        fontSize: 0.875,
    } as FontConfig,
    "textColorHighlightDimmed-Baskerville-italic-1_000": {
        color: colorSwatcher.textColorHighlightDimmed,
        fontFamily: "Baskerville",
        fontStyle: "italic",
        fontSize: 1.0,
    } as FontConfig,
    "textColorHighlightDimmed-Baskerville-italic-1_125": {
        color: colorSwatcher.textColorHighlightDimmed,
        fontFamily: "Baskerville",
        fontStyle: "italic",
        fontSize: 1.125,
    } as FontConfig,
    "textColorHighlightDimmed-Baskerville-italic-1_250": {
        color: colorSwatcher.textColorHighlightDimmed,
        fontFamily: "Baskerville",
        fontStyle: "italic",
        fontSize: 1.25,
    } as FontConfig,
    "textColorHighlightDimmed-Baskerville-italic-1_375": {
        color: colorSwatcher.textColorHighlightDimmed,
        fontFamily: "Baskerville",
        fontStyle: "italic",
        fontSize: 1.375,
    } as FontConfig,
    "textColorHighlightDimmed-Baskerville-italic-1_500": {
        color: colorSwatcher.textColorHighlightDimmed,
        fontFamily: "Baskerville",
        fontStyle: "italic",
        fontSize: 1.5,
    } as FontConfig,
    "textColorHighlightDimmed-Baskerville-italic-1_625": {
        color: colorSwatcher.textColorHighlightDimmed,
        fontFamily: "Baskerville",
        fontStyle: "italic",
        fontSize: 1.625,
    } as FontConfig,
    "textColorHighlightDimmed-Baskerville-italic-1_750": {
        color: colorSwatcher.textColorHighlightDimmed,
        fontFamily: "Baskerville",
        fontStyle: "italic",
        fontSize: 1.75,
    } as FontConfig,
    "textColorHighlightDimmed-Baskerville-italic-1_875": {
        color: colorSwatcher.textColorHighlightDimmed,
        fontFamily: "Baskerville",
        fontStyle: "italic",
        fontSize: 1.875,
    } as FontConfig,
    "textColorHighlightDimmed-Baskerville-italic-2_000": {
        color: colorSwatcher.textColorHighlightDimmed,
        fontFamily: "Baskerville",
        fontStyle: "italic",
        fontSize: 2.0,
    } as FontConfig,
    "textColorHighlightDimmed-Baskerville-italic-2_125": {
        color: colorSwatcher.textColorHighlightDimmed,
        fontFamily: "Baskerville",
        fontStyle: "italic",
        fontSize: 2.125,
    } as FontConfig,
    "textColorHighlightDimmed-Baskerville-italic-2_250": {
        color: colorSwatcher.textColorHighlightDimmed,
        fontFamily: "Baskerville",
        fontStyle: "italic",
        fontSize: 2.25,
    } as FontConfig,
    "textColorHighlightDimmed-Baskerville-italic-2_375": {
        color: colorSwatcher.textColorHighlightDimmed,
        fontFamily: "Baskerville",
        fontStyle: "italic",
        fontSize: 2.375,
    } as FontConfig,
    "textColorHighlightDimmed-Baskerville-italic-2_500": {
        color: colorSwatcher.textColorHighlightDimmed,
        fontFamily: "Baskerville",
        fontStyle: "italic",
        fontSize: 2.5,
    } as FontConfig,
    "textColorHighlightDimmed-Baskerville-italic-2_625": {
        color: colorSwatcher.textColorHighlightDimmed,
        fontFamily: "Baskerville",
        fontStyle: "italic",
        fontSize: 2.625,
    } as FontConfig,
    "textColorHighlightDimmed-Baskerville-italic-2_750": {
        color: colorSwatcher.textColorHighlightDimmed,
        fontFamily: "Baskerville",
        fontStyle: "italic",
        fontSize: 2.75,
    } as FontConfig,
    "textColorHighlightDimmed-Baskerville-italic-2_875": {
        color: colorSwatcher.textColorHighlightDimmed,
        fontFamily: "Baskerville",
        fontStyle: "italic",
        fontSize: 2.875,
    } as FontConfig,
    "textColorHighlightDimmed-Baskerville-italic-3_000": {
        color: colorSwatcher.textColorHighlightDimmed,
        fontFamily: "Baskerville",
        fontStyle: "italic",
        fontSize: 3.0,
    } as FontConfig,
    "textColorHighlightDimmed-Ridi-normal-0_750": {
        color: colorSwatcher.textColorHighlightDimmed,
        fontFamily: "Ridi",
        fontStyle: "normal",
        fontSize: 0.75,
    } as FontConfig,
    "textColorHighlightDimmed-Ridi-normal-0_875": {
        color: colorSwatcher.textColorHighlightDimmed,
        fontFamily: "Ridi",
        fontStyle: "normal",
        fontSize: 0.875,
    } as FontConfig,
    "textColorHighlightDimmed-Ridi-normal-1_000": {
        color: colorSwatcher.textColorHighlightDimmed,
        fontFamily: "Ridi",
        fontStyle: "normal",
        fontSize: 1.0,
    } as FontConfig,
    "textColorHighlightDimmed-Ridi-normal-1_125": {
        color: colorSwatcher.textColorHighlightDimmed,
        fontFamily: "Ridi",
        fontStyle: "normal",
        fontSize: 1.125,
    } as FontConfig,
    "textColorHighlightDimmed-Ridi-normal-1_250": {
        color: colorSwatcher.textColorHighlightDimmed,
        fontFamily: "Ridi",
        fontStyle: "normal",
        fontSize: 1.25,
    } as FontConfig,
    "textColorHighlightDimmed-Ridi-normal-1_375": {
        color: colorSwatcher.textColorHighlightDimmed,
        fontFamily: "Ridi",
        fontStyle: "normal",
        fontSize: 1.375,
    } as FontConfig,
    "textColorHighlightDimmed-Ridi-normal-1_500": {
        color: colorSwatcher.textColorHighlightDimmed,
        fontFamily: "Ridi",
        fontStyle: "normal",
        fontSize: 1.5,
    } as FontConfig,
    "textColorHighlightDimmed-Ridi-normal-1_625": {
        color: colorSwatcher.textColorHighlightDimmed,
        fontFamily: "Ridi",
        fontStyle: "normal",
        fontSize: 1.625,
    } as FontConfig,
    "textColorHighlightDimmed-Ridi-normal-1_750": {
        color: colorSwatcher.textColorHighlightDimmed,
        fontFamily: "Ridi",
        fontStyle: "normal",
        fontSize: 1.75,
    } as FontConfig,
    "textColorHighlightDimmed-Ridi-normal-1_875": {
        color: colorSwatcher.textColorHighlightDimmed,
        fontFamily: "Ridi",
        fontStyle: "normal",
        fontSize: 1.875,
    } as FontConfig,
    "textColorHighlightDimmed-Ridi-normal-2_000": {
        color: colorSwatcher.textColorHighlightDimmed,
        fontFamily: "Ridi",
        fontStyle: "normal",
        fontSize: 2.0,
    } as FontConfig,
    "textColorHighlightDimmed-Ridi-normal-2_125": {
        color: colorSwatcher.textColorHighlightDimmed,
        fontFamily: "Ridi",
        fontStyle: "normal",
        fontSize: 2.125,
    } as FontConfig,
    "textColorHighlightDimmed-Ridi-normal-2_250": {
        color: colorSwatcher.textColorHighlightDimmed,
        fontFamily: "Ridi",
        fontStyle: "normal",
        fontSize: 2.25,
    } as FontConfig,
    "textColorHighlightDimmed-Ridi-normal-2_375": {
        color: colorSwatcher.textColorHighlightDimmed,
        fontFamily: "Ridi",
        fontStyle: "normal",
        fontSize: 2.375,
    } as FontConfig,
    "textColorHighlightDimmed-Ridi-normal-2_500": {
        color: colorSwatcher.textColorHighlightDimmed,
        fontFamily: "Ridi",
        fontStyle: "normal",
        fontSize: 2.5,
    } as FontConfig,
    "textColorHighlightDimmed-Ridi-normal-2_625": {
        color: colorSwatcher.textColorHighlightDimmed,
        fontFamily: "Ridi",
        fontStyle: "normal",
        fontSize: 2.625,
    } as FontConfig,
    "textColorHighlightDimmed-Ridi-normal-2_750": {
        color: colorSwatcher.textColorHighlightDimmed,
        fontFamily: "Ridi",
        fontStyle: "normal",
        fontSize: 2.75,
    } as FontConfig,
    "textColorHighlightDimmed-Ridi-normal-2_875": {
        color: colorSwatcher.textColorHighlightDimmed,
        fontFamily: "Ridi",
        fontStyle: "normal",
        fontSize: 2.875,
    } as FontConfig,
    "textColorHighlightDimmed-Ridi-normal-3_000": {
        color: colorSwatcher.textColorHighlightDimmed,
        fontFamily: "Ridi",
        fontStyle: "normal",
        fontSize: 3.0,
    } as FontConfig,
    "textColorHighlightDimmed-Ridi-italic-0_750": {
        color: colorSwatcher.textColorHighlightDimmed,
        fontFamily: "Ridi",
        fontStyle: "italic",
        fontSize: 0.75,
    } as FontConfig,
    "textColorHighlightDimmed-Ridi-italic-0_875": {
        color: colorSwatcher.textColorHighlightDimmed,
        fontFamily: "Ridi",
        fontStyle: "italic",
        fontSize: 0.875,
    } as FontConfig,
    "textColorHighlightDimmed-Ridi-italic-1_000": {
        color: colorSwatcher.textColorHighlightDimmed,
        fontFamily: "Ridi",
        fontStyle: "italic",
        fontSize: 1.0,
    } as FontConfig,
    "textColorHighlightDimmed-Ridi-italic-1_125": {
        color: colorSwatcher.textColorHighlightDimmed,
        fontFamily: "Ridi",
        fontStyle: "italic",
        fontSize: 1.125,
    } as FontConfig,
    "textColorHighlightDimmed-Ridi-italic-1_250": {
        color: colorSwatcher.textColorHighlightDimmed,
        fontFamily: "Ridi",
        fontStyle: "italic",
        fontSize: 1.25,
    } as FontConfig,
    "textColorHighlightDimmed-Ridi-italic-1_375": {
        color: colorSwatcher.textColorHighlightDimmed,
        fontFamily: "Ridi",
        fontStyle: "italic",
        fontSize: 1.375,
    } as FontConfig,
    "textColorHighlightDimmed-Ridi-italic-1_500": {
        color: colorSwatcher.textColorHighlightDimmed,
        fontFamily: "Ridi",
        fontStyle: "italic",
        fontSize: 1.5,
    } as FontConfig,
    "textColorHighlightDimmed-Ridi-italic-1_625": {
        color: colorSwatcher.textColorHighlightDimmed,
        fontFamily: "Ridi",
        fontStyle: "italic",
        fontSize: 1.625,
    } as FontConfig,
    "textColorHighlightDimmed-Ridi-italic-1_750": {
        color: colorSwatcher.textColorHighlightDimmed,
        fontFamily: "Ridi",
        fontStyle: "italic",
        fontSize: 1.75,
    } as FontConfig,
    "textColorHighlightDimmed-Ridi-italic-1_875": {
        color: colorSwatcher.textColorHighlightDimmed,
        fontFamily: "Ridi",
        fontStyle: "italic",
        fontSize: 1.875,
    } as FontConfig,
    "textColorHighlightDimmed-Ridi-italic-2_000": {
        color: colorSwatcher.textColorHighlightDimmed,
        fontFamily: "Ridi",
        fontStyle: "italic",
        fontSize: 2.0,
    } as FontConfig,
    "textColorHighlightDimmed-Ridi-italic-2_125": {
        color: colorSwatcher.textColorHighlightDimmed,
        fontFamily: "Ridi",
        fontStyle: "italic",
        fontSize: 2.125,
    } as FontConfig,
    "textColorHighlightDimmed-Ridi-italic-2_250": {
        color: colorSwatcher.textColorHighlightDimmed,
        fontFamily: "Ridi",
        fontStyle: "italic",
        fontSize: 2.25,
    } as FontConfig,
    "textColorHighlightDimmed-Ridi-italic-2_375": {
        color: colorSwatcher.textColorHighlightDimmed,
        fontFamily: "Ridi",
        fontStyle: "italic",
        fontSize: 2.375,
    } as FontConfig,
    "textColorHighlightDimmed-Ridi-italic-2_500": {
        color: colorSwatcher.textColorHighlightDimmed,
        fontFamily: "Ridi",
        fontStyle: "italic",
        fontSize: 2.5,
    } as FontConfig,
    "textColorHighlightDimmed-Ridi-italic-2_625": {
        color: colorSwatcher.textColorHighlightDimmed,
        fontFamily: "Ridi",
        fontStyle: "italic",
        fontSize: 2.625,
    } as FontConfig,
    "textColorHighlightDimmed-Ridi-italic-2_750": {
        color: colorSwatcher.textColorHighlightDimmed,
        fontFamily: "Ridi",
        fontStyle: "italic",
        fontSize: 2.75,
    } as FontConfig,
    "textColorHighlightDimmed-Ridi-italic-2_875": {
        color: colorSwatcher.textColorHighlightDimmed,
        fontFamily: "Ridi",
        fontStyle: "italic",
        fontSize: 2.875,
    } as FontConfig,
    "textColorHighlightDimmed-Ridi-italic-3_000": {
        color: colorSwatcher.textColorHighlightDimmed,
        fontFamily: "Ridi",
        fontStyle: "italic",
        fontSize: 3.0,
    } as FontConfig,
    "textColor-Baskerville-normal-0_750": {
        color: colorSwatcher.textColor,
        fontFamily: "Baskerville",
        fontStyle: "normal",
        fontSize: 0.75,
    } as FontConfig,
    "textColor-Baskerville-normal-0_875": {
        color: colorSwatcher.textColor,
        fontFamily: "Baskerville",
        fontStyle: "normal",
        fontSize: 0.875,
    } as FontConfig,
    "textColor-Baskerville-normal-1_000": {
        color: colorSwatcher.textColor,
        fontFamily: "Baskerville",
        fontStyle: "normal",
        fontSize: 1.0,
    } as FontConfig,
    "textColor-Baskerville-normal-1_125": {
        color: colorSwatcher.textColor,
        fontFamily: "Baskerville",
        fontStyle: "normal",
        fontSize: 1.125,
    } as FontConfig,
    "textColor-Baskerville-normal-1_250": {
        color: colorSwatcher.textColor,
        fontFamily: "Baskerville",
        fontStyle: "normal",
        fontSize: 1.25,
    } as FontConfig,
    "textColor-Baskerville-normal-1_375": {
        color: colorSwatcher.textColor,
        fontFamily: "Baskerville",
        fontStyle: "normal",
        fontSize: 1.375,
    } as FontConfig,
    "textColor-Baskerville-normal-1_500": {
        color: colorSwatcher.textColor,
        fontFamily: "Baskerville",
        fontStyle: "normal",
        fontSize: 1.5,
    } as FontConfig,
    "textColor-Baskerville-normal-1_625": {
        color: colorSwatcher.textColor,
        fontFamily: "Baskerville",
        fontStyle: "normal",
        fontSize: 1.625,
    } as FontConfig,
    "textColor-Baskerville-normal-1_750": {
        color: colorSwatcher.textColor,
        fontFamily: "Baskerville",
        fontStyle: "normal",
        fontSize: 1.75,
    } as FontConfig,
    "textColor-Baskerville-normal-1_875": {
        color: colorSwatcher.textColor,
        fontFamily: "Baskerville",
        fontStyle: "normal",
        fontSize: 1.875,
    } as FontConfig,
    "textColor-Baskerville-normal-2_000": {
        color: colorSwatcher.textColor,
        fontFamily: "Baskerville",
        fontStyle: "normal",
        fontSize: 2.0,
    } as FontConfig,
    "textColor-Baskerville-normal-2_125": {
        color: colorSwatcher.textColor,
        fontFamily: "Baskerville",
        fontStyle: "normal",
        fontSize: 2.125,
    } as FontConfig,
    "textColor-Baskerville-normal-2_250": {
        color: colorSwatcher.textColor,
        fontFamily: "Baskerville",
        fontStyle: "normal",
        fontSize: 2.25,
    } as FontConfig,
    "textColor-Baskerville-normal-2_375": {
        color: colorSwatcher.textColor,
        fontFamily: "Baskerville",
        fontStyle: "normal",
        fontSize: 2.375,
    } as FontConfig,
    "textColor-Baskerville-normal-2_500": {
        color: colorSwatcher.textColor,
        fontFamily: "Baskerville",
        fontStyle: "normal",
        fontSize: 2.5,
    } as FontConfig,
    "textColor-Baskerville-normal-2_625": {
        color: colorSwatcher.textColor,
        fontFamily: "Baskerville",
        fontStyle: "normal",
        fontSize: 2.625,
    } as FontConfig,
    "textColor-Baskerville-normal-2_750": {
        color: colorSwatcher.textColor,
        fontFamily: "Baskerville",
        fontStyle: "normal",
        fontSize: 2.75,
    } as FontConfig,
    "textColor-Baskerville-normal-2_875": {
        color: colorSwatcher.textColor,
        fontFamily: "Baskerville",
        fontStyle: "normal",
        fontSize: 2.875,
    } as FontConfig,
    "textColor-Baskerville-normal-3_000": {
        color: colorSwatcher.textColor,
        fontFamily: "Baskerville",
        fontStyle: "normal",
        fontSize: 3.0,
    } as FontConfig,
    "textColor-Baskerville-italic-0_750": {
        color: colorSwatcher.textColor,
        fontFamily: "Baskerville",
        fontStyle: "italic",
        fontSize: 0.75,
    } as FontConfig,
    "textColor-Baskerville-italic-0_875": {
        color: colorSwatcher.textColor,
        fontFamily: "Baskerville",
        fontStyle: "italic",
        fontSize: 0.875,
    } as FontConfig,
    "textColor-Baskerville-italic-1_000": {
        color: colorSwatcher.textColor,
        fontFamily: "Baskerville",
        fontStyle: "italic",
        fontSize: 1.0,
    } as FontConfig,
    "textColor-Baskerville-italic-1_125": {
        color: colorSwatcher.textColor,
        fontFamily: "Baskerville",
        fontStyle: "italic",
        fontSize: 1.125,
    } as FontConfig,
    "textColor-Baskerville-italic-1_250": {
        color: colorSwatcher.textColor,
        fontFamily: "Baskerville",
        fontStyle: "italic",
        fontSize: 1.25,
    } as FontConfig,
    "textColor-Baskerville-italic-1_375": {
        color: colorSwatcher.textColor,
        fontFamily: "Baskerville",
        fontStyle: "italic",
        fontSize: 1.375,
    } as FontConfig,
    "textColor-Baskerville-italic-1_500": {
        color: colorSwatcher.textColor,
        fontFamily: "Baskerville",
        fontStyle: "italic",
        fontSize: 1.5,
    } as FontConfig,
    "textColor-Baskerville-italic-1_625": {
        color: colorSwatcher.textColor,
        fontFamily: "Baskerville",
        fontStyle: "italic",
        fontSize: 1.625,
    } as FontConfig,
    "textColor-Baskerville-italic-1_750": {
        color: colorSwatcher.textColor,
        fontFamily: "Baskerville",
        fontStyle: "italic",
        fontSize: 1.75,
    } as FontConfig,
    "textColor-Baskerville-italic-1_875": {
        color: colorSwatcher.textColor,
        fontFamily: "Baskerville",
        fontStyle: "italic",
        fontSize: 1.875,
    } as FontConfig,
    "textColor-Baskerville-italic-2_000": {
        color: colorSwatcher.textColor,
        fontFamily: "Baskerville",
        fontStyle: "italic",
        fontSize: 2.0,
    } as FontConfig,
    "textColor-Baskerville-italic-2_125": {
        color: colorSwatcher.textColor,
        fontFamily: "Baskerville",
        fontStyle: "italic",
        fontSize: 2.125,
    } as FontConfig,
    "textColor-Baskerville-italic-2_250": {
        color: colorSwatcher.textColor,
        fontFamily: "Baskerville",
        fontStyle: "italic",
        fontSize: 2.25,
    } as FontConfig,
    "textColor-Baskerville-italic-2_375": {
        color: colorSwatcher.textColor,
        fontFamily: "Baskerville",
        fontStyle: "italic",
        fontSize: 2.375,
    } as FontConfig,
    "textColor-Baskerville-italic-2_500": {
        color: colorSwatcher.textColor,
        fontFamily: "Baskerville",
        fontStyle: "italic",
        fontSize: 2.5,
    } as FontConfig,
    "textColor-Baskerville-italic-2_625": {
        color: colorSwatcher.textColor,
        fontFamily: "Baskerville",
        fontStyle: "italic",
        fontSize: 2.625,
    } as FontConfig,
    "textColor-Baskerville-italic-2_750": {
        color: colorSwatcher.textColor,
        fontFamily: "Baskerville",
        fontStyle: "italic",
        fontSize: 2.75,
    } as FontConfig,
    "textColor-Baskerville-italic-2_875": {
        color: colorSwatcher.textColor,
        fontFamily: "Baskerville",
        fontStyle: "italic",
        fontSize: 2.875,
    } as FontConfig,
    "textColor-Baskerville-italic-3_000": {
        color: colorSwatcher.textColor,
        fontFamily: "Baskerville",
        fontStyle: "italic",
        fontSize: 3.0,
    } as FontConfig,
    "textColor-Ridi-normal-0_750": {
        color: colorSwatcher.textColor,
        fontFamily: "Ridi",
        fontStyle: "normal",
        fontSize: 0.75,
    } as FontConfig,
    "textColor-Ridi-normal-0_875": {
        color: colorSwatcher.textColor,
        fontFamily: "Ridi",
        fontStyle: "normal",
        fontSize: 0.875,
    } as FontConfig,
    "textColor-Ridi-normal-1_000": {
        color: colorSwatcher.textColor,
        fontFamily: "Ridi",
        fontStyle: "normal",
        fontSize: 1.0,
    } as FontConfig,
    "textColor-Ridi-normal-1_125": {
        color: colorSwatcher.textColor,
        fontFamily: "Ridi",
        fontStyle: "normal",
        fontSize: 1.125,
    } as FontConfig,
    "textColor-Ridi-normal-1_250": {
        color: colorSwatcher.textColor,
        fontFamily: "Ridi",
        fontStyle: "normal",
        fontSize: 1.25,
    } as FontConfig,
    "textColor-Ridi-normal-1_375": {
        color: colorSwatcher.textColor,
        fontFamily: "Ridi",
        fontStyle: "normal",
        fontSize: 1.375,
    } as FontConfig,
    "textColor-Ridi-normal-1_500": {
        color: colorSwatcher.textColor,
        fontFamily: "Ridi",
        fontStyle: "normal",
        fontSize: 1.5,
    } as FontConfig,
    "textColor-Ridi-normal-1_625": {
        color: colorSwatcher.textColor,
        fontFamily: "Ridi",
        fontStyle: "normal",
        fontSize: 1.625,
    } as FontConfig,
    "textColor-Ridi-normal-1_750": {
        color: colorSwatcher.textColor,
        fontFamily: "Ridi",
        fontStyle: "normal",
        fontSize: 1.75,
    } as FontConfig,
    "textColor-Ridi-normal-1_875": {
        color: colorSwatcher.textColor,
        fontFamily: "Ridi",
        fontStyle: "normal",
        fontSize: 1.875,
    } as FontConfig,
    "textColor-Ridi-normal-2_000": {
        color: colorSwatcher.textColor,
        fontFamily: "Ridi",
        fontStyle: "normal",
        fontSize: 2.0,
    } as FontConfig,
    "textColor-Ridi-normal-2_125": {
        color: colorSwatcher.textColor,
        fontFamily: "Ridi",
        fontStyle: "normal",
        fontSize: 2.125,
    } as FontConfig,
    "textColor-Ridi-normal-2_250": {
        color: colorSwatcher.textColor,
        fontFamily: "Ridi",
        fontStyle: "normal",
        fontSize: 2.25,
    } as FontConfig,
    "textColor-Ridi-normal-2_375": {
        color: colorSwatcher.textColor,
        fontFamily: "Ridi",
        fontStyle: "normal",
        fontSize: 2.375,
    } as FontConfig,
    "textColor-Ridi-normal-2_500": {
        color: colorSwatcher.textColor,
        fontFamily: "Ridi",
        fontStyle: "normal",
        fontSize: 2.5,
    } as FontConfig,
    "textColor-Ridi-normal-2_625": {
        color: colorSwatcher.textColor,
        fontFamily: "Ridi",
        fontStyle: "normal",
        fontSize: 2.625,
    } as FontConfig,
    "textColor-Ridi-normal-2_750": {
        color: colorSwatcher.textColor,
        fontFamily: "Ridi",
        fontStyle: "normal",
        fontSize: 2.75,
    } as FontConfig,
    "textColor-Ridi-normal-2_875": {
        color: colorSwatcher.textColor,
        fontFamily: "Ridi",
        fontStyle: "normal",
        fontSize: 2.875,
    } as FontConfig,
    "textColor-Ridi-normal-3_000": {
        color: colorSwatcher.textColor,
        fontFamily: "Ridi",
        fontStyle: "normal",
        fontSize: 3.0,
    } as FontConfig,
    "textColor-Ridi-italic-0_750": {
        color: colorSwatcher.textColor,
        fontFamily: "Ridi",
        fontStyle: "italic",
        fontSize: 0.75,
    } as FontConfig,
    "textColor-Ridi-italic-0_875": {
        color: colorSwatcher.textColor,
        fontFamily: "Ridi",
        fontStyle: "italic",
        fontSize: 0.875,
    } as FontConfig,
    "textColor-Ridi-italic-1_000": {
        color: colorSwatcher.textColor,
        fontFamily: "Ridi",
        fontStyle: "italic",
        fontSize: 1.0,
    } as FontConfig,
    "textColor-Ridi-italic-1_125": {
        color: colorSwatcher.textColor,
        fontFamily: "Ridi",
        fontStyle: "italic",
        fontSize: 1.125,
    } as FontConfig,
    "textColor-Ridi-italic-1_250": {
        color: colorSwatcher.textColor,
        fontFamily: "Ridi",
        fontStyle: "italic",
        fontSize: 1.25,
    } as FontConfig,
    "textColor-Ridi-italic-1_375": {
        color: colorSwatcher.textColor,
        fontFamily: "Ridi",
        fontStyle: "italic",
        fontSize: 1.375,
    } as FontConfig,
    "textColor-Ridi-italic-1_500": {
        color: colorSwatcher.textColor,
        fontFamily: "Ridi",
        fontStyle: "italic",
        fontSize: 1.5,
    } as FontConfig,
    "textColor-Ridi-italic-1_625": {
        color: colorSwatcher.textColor,
        fontFamily: "Ridi",
        fontStyle: "italic",
        fontSize: 1.625,
    } as FontConfig,
    "textColor-Ridi-italic-1_750": {
        color: colorSwatcher.textColor,
        fontFamily: "Ridi",
        fontStyle: "italic",
        fontSize: 1.75,
    } as FontConfig,
    "textColor-Ridi-italic-1_875": {
        color: colorSwatcher.textColor,
        fontFamily: "Ridi",
        fontStyle: "italic",
        fontSize: 1.875,
    } as FontConfig,
    "textColor-Ridi-italic-2_000": {
        color: colorSwatcher.textColor,
        fontFamily: "Ridi",
        fontStyle: "italic",
        fontSize: 2.0,
    } as FontConfig,
    "textColor-Ridi-italic-2_125": {
        color: colorSwatcher.textColor,
        fontFamily: "Ridi",
        fontStyle: "italic",
        fontSize: 2.125,
    } as FontConfig,
    "textColor-Ridi-italic-2_250": {
        color: colorSwatcher.textColor,
        fontFamily: "Ridi",
        fontStyle: "italic",
        fontSize: 2.25,
    } as FontConfig,
    "textColor-Ridi-italic-2_375": {
        color: colorSwatcher.textColor,
        fontFamily: "Ridi",
        fontStyle: "italic",
        fontSize: 2.375,
    } as FontConfig,
    "textColor-Ridi-italic-2_500": {
        color: colorSwatcher.textColor,
        fontFamily: "Ridi",
        fontStyle: "italic",
        fontSize: 2.5,
    } as FontConfig,
    "textColor-Ridi-italic-2_625": {
        color: colorSwatcher.textColor,
        fontFamily: "Ridi",
        fontStyle: "italic",
        fontSize: 2.625,
    } as FontConfig,
    "textColor-Ridi-italic-2_750": {
        color: colorSwatcher.textColor,
        fontFamily: "Ridi",
        fontStyle: "italic",
        fontSize: 2.75,
    } as FontConfig,
    "textColor-Ridi-italic-2_875": {
        color: colorSwatcher.textColor,
        fontFamily: "Ridi",
        fontStyle: "italic",
        fontSize: 2.875,
    } as FontConfig,
    "textColor-Ridi-italic-3_000": {
        color: colorSwatcher.textColor,
        fontFamily: "Ridi",
        fontStyle: "italic",
        fontSize: 3.0,
    } as FontConfig,
};
